services:
  - type: web
    name: proyectodjango
    env: python
    buildCommand: |
      pip install -r requirements.txt &&
      python manage.py migrate &&
      python manage.py collectstatic --noinput
    startCommand: "gunicorn mi_sitio.wsgi:application"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: mi_sitio.settings
      - key: DATABASE_URL
        value: postgresql://whitespacedb_user:P3ji0o2UW4cZxAnVWBzTgVUJh2wAZPWv@dpg-d1e8ksh5pdvs73bpv8vg-a.oregon-postgres.render.com/whitespacedb