# Generated by Django 5.2 on 2025-06-24 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_parcial', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultas',
            name='categoria',
            field=models.CharField(default='Consulta General', max_length=50),
        ),
    ]

def agregar_usuario_permitido(apps, schema_editor):
    UsuariosPermitidos = apps.get_model('mi_parcial', 'UsuariosPermitidos')
    UsuariosPermitidos.objects.create(
        nombre='Ana Villegas',
        email='annavillegas@live.com.ar',
        codigo_validacion='123ABC'
    )
