# Generated by Django 5.2 on 2025-06-24 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_parcial', '0002_consultas_categoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsuariosPermitidos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('codigo_validacion', models.CharField(max_length=20)),
            ],
        ),
    ]
