# Generated by Django 5.2 on 2025-06-25 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_parcial', '0004_usuariopersonalizado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuariospermitidos',
            name='codigo_validacion',
            field=models.CharField(max_length=10),
        ),
        migrations.DeleteModel(
            name='UsuarioPersonalizado',
        ),
    ]
